### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by deckar01** [Akrog/pinliner#2]
There are a few features currently in use that are have breaking changes in python 3. I was able to patch my local copy with minimal effort.

- `pyinliner/pyinliner.py`
  - _Line 42_: `long` has been merged into `int`.
    - [`int` is valid in python 2 and 3.](http://python-future.org/compatible_idioms.html#long-integers)
  - _Line 145_: The `version` argument for `argparse.ArgumentParser` which `MyParser` extends was deprecated in python 2. Use `parser.add_argument('--version', action='version', version=__version__)` instead.
    - See https://docs.python.org/2/library/argparse.html#upgrading-optparse-code
- `pyinliner/import.template`
  - _Line 90_: `exec A in B` has been replaced with `exec(A, B)`
    - [`exec()` is valid in python 2 and 3.](http://python-future.org/compatible_idioms.html#exec)
  - _Line 115_: `exec A in B` has been replaced with `exec(A, B)`
    - [`exec()` is valid in python 2 and 3.](http://python-future.org/compatible_idioms.html#exec)
  - _Line 169_: `exec A` has been replaced with `exec(A, globals())`
    - [`exec()` is valid in python 2 and 3.](http://python-future.org/compatible_idioms.html#exec)

Would you be interested in supporting python 3 if I opened a PR with these changes?

**Comment by Akrog** [comment]
Hey, sorry for the late reply.

**I would definitely be interested!**
